.TH vumz 1 "July 2024" "vumz 0.1" "User Commands"
.SH NAME
vumz \- \fBVU\fR \fBM\fReter Visuali\fBZ\fRer
.SH SYNOPSIS
.B vumz
.RI [ OPTIONS ]
.SH DESCRIPTION
.B vumz
is a simple command-line VU meter visualizer that uses ncurses and PipeWire to display the audio levels of the left and right audio channels.

.SH OPTIONS
.TP
.B \-D, \-\-debug
Enable debug mode, which prints useful data.
.TP
.B \-S, \-\-screensaver
Enable screensaver mode, allowing you to press any key to quit.
.TP
.B \-h, \-\-help
Display a help message and exit.

.SH INTERACTIVE COMMANDS
The noise reduction factor controls how smoothly the VU meter responds to changes in audio levels.
.TP
.B KEY_LEFT
Switch to previous color theme.
.TP
.B KEY_RIGHT
Switch to next color theme.
.TP
.B KEY_UP
Increase noise reduction.
.TP
.B KEY_DOWN
Decrease noise reduction.
.TP
.B d
Toggle debug mode.
.TP
.B q
Quit the visualizer.
.TP
.B Escape
Quit the visualizer.

.SH EXAMPLES
.TP
.B vumz
.br
Start the VU meter visualizer.
.BR
.TP
.B vumz \-D
.br
Start the VU meter visualizer in debug mode.
.BR
.TP
.B vumz \-S
.br
Start the VU meter visualizer in screensaver mode.
.BR

.SH BUGS
Please document if you find any bugs.

.SH AUTHOR
Ionel Pop <ionelalexandru.pop@gmail.com>

.SH SEE ALSO
.BR pipewire (1),
.BR ncurses (3)
